version: 2
updates:
  # Tự động cập nhật thư viện cho Frontend (NPM)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "frontend"

  # Tự động cập nhật thư viện cho Backend (.NET NuGet)
  - package-ecosystem: "nuget"
    directory: "/backend/src"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "backend"

  # Tự động cập nhật Image trong Dockerfile và Docker-compose
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "devops"
