// <auto-generated />
using System;
using System.Collections.Generic;
using CraftVision.Domain.Enums;
using CraftVision.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace CraftVision.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260713125741_SeedImagesAgain")]
    partial class SeedImagesAgain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "difficulty_enum", new[] { "Easy", "Hard", "Medium" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "file_type_enum", new[] { "Image", "Video" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "gift_status_enum", new[] { "Active", "Disabled", "Draft" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "material_unit_enum", new[] { "gram", "liter", "meter", "pack", "piece", "set" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "media_type_enum", new[] { "Image", "Video" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "message_role_enum", new[] { "Assistant", "System", "User" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "message_source_enum", new[] { "AI", "Manual" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "model_type_enum", new[] { "GLB", "GLTF", "USDZ" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "nfc_status_enum", new[] { "Available", "Disabled", "Lost", "Reserved", "Sold" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "option_level_enum", new[] { "Advanced", "Basic", "Intermediate" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "order_status_enum", new[] { "Cancelled", "Delivered", "Pending", "Processing", "Producing", "ReadyToShip", "Shipped", "WaitingProduction" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_method_enum", new[] { "Cod", "None" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_status_enum", new[] { "Failed", "Paid", "Refunded", "Unpaid" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "product_type_enum", new[] { "InStock", "PreOrder" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "request_status_enum", new[] { "Completed", "Failed", "Pending" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_tier_enum", new[] { "Free", "Premium" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CraftVision.Domain.Entities.Ai3dRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreditCost")
                        .HasColumnType("integer")
                        .HasColumnName("credit_cost");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("locked_by");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_version");

                    b.Property<int?>("Progress")
                        .HasColumnType("integer")
                        .HasColumnName("progress");

                    b.Property<string>("ResultModelUrl")
                        .HasColumnType("text")
                        .HasColumnName("result_model_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("task_type");

                    b.Property<string>("TripoTaskId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("tripo_task_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UploadedFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_file_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_ai_3d_requests");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_ai_3d_requests_idempotency_key");

                    b.HasIndex("TripoTaskId")
                        .IsUnique()
                        .HasDatabaseName("ix_ai_3d_requests_tripo_task_id");

                    b.HasIndex("UploadedFileId")
                        .HasDatabaseName("ix_ai_3d_requests_uploaded_file_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ai_3d_requests_user_id");

                    b.HasIndex("Status", "LockedUntil")
                        .HasDatabaseName("ix_ai_3d_requests_status_locked_until")
                        .HasFilter("status IN ('queued', 'running')");

                    b.ToTable("ai_3d_requests", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.AiChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ImageFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_file_id");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.PrimitiveCollection<List<Guid>>("RetrievedContextIds")
                        .HasColumnType("uuid[]")
                        .HasColumnName("retrieved_context_ids");

                    b.Property<MessageRole>("Role")
                        .HasColumnType("message_role_enum")
                        .HasColumnName("role");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_used");

                    b.HasKey("Id")
                        .HasName("pk_ai_chat_messages");

                    b.HasIndex("ImageFileId")
                        .HasDatabaseName("ix_ai_chat_messages_image_file_id");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("ix_ai_chat_messages_request_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_ai_chat_messages_session_id");

                    b.ToTable("ai_chat_messages", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.AiChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_ai_chat_sessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ai_chat_sessions_user_id");

                    b.ToTable("ai_chat_sessions", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.AiRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("ParsedIntent")
                        .HasColumnType("jsonb")
                        .HasColumnName("parsed_intent");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_text");

                    b.Property<int?>("RequestTokens")
                        .HasColumnType("integer")
                        .HasColumnName("request_tokens");

                    b.Property<int?>("ResponseTokens")
                        .HasColumnType("integer")
                        .HasColumnName("response_tokens");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<RequestStatus>("Status")
                        .HasColumnType("request_status_enum")
                        .HasColumnName("status");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("integer")
                        .HasColumnName("total_tokens");

                    b.Property<Guid?>("UploadedFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_file_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_ai_requests");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_ai_requests_session_id");

                    b.HasIndex("UploadedFileId")
                        .HasDatabaseName("ix_ai_requests_uploaded_file_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ai_requests_user_id");

                    b.ToTable("ai_requests", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.DiyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Difficulty?>("Difficulty")
                        .HasColumnType("difficulty_enum")
                        .HasColumnName("difficulty");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_cost");

                    b.Property<int?>("EstimatedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_minutes");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_selected");

                    b.Property<string>("MaterialsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("materials_json");

                    b.Property<string>("Occasion")
                        .HasColumnType("text")
                        .HasColumnName("occasion");

                    b.Property<OptionLevel?>("OptionLevel")
                        .HasColumnType("option_level_enum")
                        .HasColumnName("option_level");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("ShareSlug")
                        .HasColumnType("text")
                        .HasColumnName("share_slug");

                    b.Property<string>("StepsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("steps_json");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_diy_plans");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_diy_plans_request_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_diy_plans_user_id");

                    b.ToTable("diy_plans", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.DiyPlanMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DiyPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("diy_plan_id");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<string>("NameSnapshot")
                        .HasColumnType("text")
                        .HasColumnName("name_snapshot");

                    b.Property<decimal?>("PriceSnapshot")
                        .HasColumnType("numeric")
                        .HasColumnName("price_snapshot");

                    b.Property<string>("PurchaseUrlSnapshot")
                        .HasColumnType("text")
                        .HasColumnName("purchase_url_snapshot");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<string>("SearchKeywordsSnapshot")
                        .HasColumnType("text")
                        .HasColumnName("search_keywords_snapshot");

                    b.HasKey("Id")
                        .HasName("pk_diy_plan_materials");

                    b.HasIndex("DiyPlanId")
                        .HasDatabaseName("ix_diy_plan_materials_diy_plan_id");

                    b.HasIndex("MaterialId")
                        .HasDatabaseName("ix_diy_plan_materials_material_id");

                    b.ToTable("diy_plan_materials", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.DiyPlanTutorial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DiyPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("diy_plan_id");

                    b.Property<Guid>("TutorialId")
                        .HasColumnType("uuid")
                        .HasColumnName("tutorial_id");

                    b.HasKey("Id")
                        .HasName("pk_diy_plan_tutorials");

                    b.HasIndex("DiyPlanId")
                        .HasDatabaseName("ix_diy_plan_tutorials_diy_plan_id");

                    b.HasIndex("TutorialId")
                        .HasDatabaseName("ix_diy_plan_tutorials_tutorial_id");

                    b.ToTable("diy_plan_tutorials", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.Gift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GiftTitle")
                        .HasColumnType("text")
                        .HasColumnName("gift_title");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<MessageSource>("MessageSource")
                        .HasColumnType("message_source_enum")
                        .HasColumnName("message_source");

                    b.Property<Guid>("NfcTagId")
                        .HasColumnType("uuid")
                        .HasColumnName("nfc_tag_id");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_item_id");

                    b.Property<string>("PreviewImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("preview_image_url");

                    b.Property<string>("ReceiverName")
                        .HasColumnType("text")
                        .HasColumnName("receiver_name");

                    b.Property<string>("SenderName")
                        .HasColumnType("text")
                        .HasColumnName("sender_name");

                    b.Property<GiftStatus>("Status")
                        .HasColumnType("gift_status_enum")
                        .HasColumnName("status");

                    b.Property<string>("Theme")
                        .HasColumnType("text")
                        .HasColumnName("theme");

                    b.Property<ModelType?>("ThreeDModelType")
                        .HasColumnType("model_type_enum")
                        .HasColumnName("three_d_model_type");

                    b.Property<string>("ThreeDModelUrl")
                        .HasColumnType("text")
                        .HasColumnName("three_d_model_url");

                    b.Property<string>("ThreeDPrompt")
                        .HasColumnType("text")
                        .HasColumnName("three_d_prompt");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_gifts");

                    b.HasIndex("NfcTagId")
                        .IsUnique()
                        .HasDatabaseName("ix_gifts_nfc_tag_id");

                    b.HasIndex("OrderItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_gifts_order_item_id");

                    b.ToTable("gifts", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.GiftAiProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalContext")
                        .HasColumnType("text")
                        .HasColumnName("additional_context");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DesignPrompt")
                        .HasColumnType("text")
                        .HasColumnName("design_prompt");

                    b.Property<string>("EmojiLevel")
                        .HasColumnType("text")
                        .HasColumnName("emoji_level");

                    b.Property<Guid>("GiftCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("gift_category_id");

                    b.Property<Guid>("GiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("gift_id");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("MessageLength")
                        .HasColumnType("text")
                        .HasColumnName("message_length");

                    b.Property<string>("Relationship")
                        .HasColumnType("text")
                        .HasColumnName("relationship");

                    b.Property<string>("WritingStyle")
                        .HasColumnType("text")
                        .HasColumnName("writing_style");

                    b.HasKey("Id")
                        .HasName("pk_gift_ai_profiles");

                    b.HasIndex("GiftCategoryId")
                        .HasDatabaseName("ix_gift_ai_profiles_gift_category_id");

                    b.HasIndex("GiftId")
                        .IsUnique()
                        .HasDatabaseName("ix_gift_ai_profiles_gift_id");

                    b.ToTable("gift_ai_profiles", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.GiftCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PromptTemplate")
                        .HasColumnType("text")
                        .HasColumnName("prompt_template");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_gift_categories");

                    b.ToTable("gift_categories", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.GiftMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Caption")
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<Guid>("GiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("gift_id");

                    b.Property<MediaType>("MediaType")
                        .HasColumnType("media_type_enum")
                        .HasColumnName("media_type");

                    b.HasKey("Id")
                        .HasName("pk_gift_media");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_gift_media_file_id");

                    b.HasIndex("GiftId")
                        .HasDatabaseName("ix_gift_media_gift_id");

                    b.ToTable("gift_media", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.GiftSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Difficulty?>("Difficulty")
                        .HasColumnType("difficulty_enum")
                        .HasColumnName("difficulty");

                    b.Property<string>("EstimatedCostRange")
                        .HasColumnType("text")
                        .HasColumnName("estimated_cost_range");

                    b.Property<string>("EstimatedTime")
                        .HasColumnType("text")
                        .HasColumnName("estimated_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.HasKey("Id")
                        .HasName("pk_gift_suggestions");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("ix_gift_suggestions_request_id");

                    b.ToTable("gift_suggestions", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.ImageAnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("numeric")
                        .HasColumnName("confidence_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<List<string>>("DetectedColors")
                        .HasColumnType("text[]")
                        .HasColumnName("detected_colors");

                    b.PrimitiveCollection<List<string>>("DetectedMaterials")
                        .HasColumnType("text[]")
                        .HasColumnName("detected_materials");

                    b.PrimitiveCollection<List<string>>("DetectedTechnique")
                        .HasColumnType("text[]")
                        .HasColumnName("detected_technique");

                    b.Property<string>("RawVisionResponse")
                        .HasColumnType("text")
                        .HasColumnName("raw_vision_response");

                    b.Property<Guid>("UploadedFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_file_id");

                    b.HasKey("Id")
                        .HasName("pk_image_analysis_results");

                    b.HasIndex("UploadedFileId")
                        .IsUnique()
                        .HasDatabaseName("ix_image_analysis_results_uploaded_file_id");

                    b.ToTable("image_analysis_results", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.KnowledgeMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("CurrentPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("current_price");

                    b.Property<Difficulty?>("Difficulty")
                        .HasColumnType("difficulty_enum")
                        .HasColumnName("difficulty");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_cost");

                    b.Property<int?>("EstimatedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_minutes");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checked_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Occasion")
                        .HasColumnType("text")
                        .HasColumnName("occasion");

                    b.Property<string>("PurchaseUrl")
                        .HasColumnType("text")
                        .HasColumnName("purchase_url");

                    b.Property<string>("SearchKeywords")
                        .HasColumnType("text")
                        .HasColumnName("search_keywords");

                    b.Property<MaterialUnit?>("Unit")
                        .HasColumnType("material_unit_enum")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_materials");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_knowledge_materials_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("knowledge_materials", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.KnowledgeTutorial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Difficulty?>("Difficulty")
                        .HasColumnType("difficulty_enum")
                        .HasColumnName("difficulty");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_cost");

                    b.Property<int?>("EstimatedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_minutes");

                    b.Property<string>("Occasion")
                        .HasColumnType("text")
                        .HasColumnName("occasion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text")
                        .HasColumnName("video_url");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_tutorials");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_knowledge_tutorials_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("knowledge_tutorials", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.MessageTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GiftCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("gift_category_id");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean")
                        .HasColumnName("is_premium");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_message_templates");

                    b.HasIndex("GiftCategoryId")
                        .HasDatabaseName("ix_message_templates_gift_category_id");

                    b.ToTable("message_templates", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.NfcTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("secret_key");

                    b.Property<NfcStatus>("Status")
                        .HasColumnType("nfc_status_enum")
                        .HasColumnName("status");

                    b.Property<string>("TagCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_nfc_tags");

                    b.ToTable("nfc_tags", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_code");

                    b.Property<OrderStatus>("OrderStatus")
                        .HasColumnType("order_status_enum")
                        .HasColumnName("order_status");

                    b.Property<PaymentMethod>("PaymentMethod")
                        .HasColumnType("payment_method_enum")
                        .HasColumnName("payment_method");

                    b.Property<PaymentStatus>("PaymentStatus")
                        .HasColumnType("payment_status_enum")
                        .HasColumnName("payment_status");

                    b.Property<string>("ReceiverAddress")
                        .HasColumnType("text")
                        .HasColumnName("receiver_address");

                    b.Property<string>("ReceiverName")
                        .HasColumnType("text")
                        .HasColumnName("receiver_name");

                    b.Property<string>("ReceiverPhone")
                        .HasColumnType("text")
                        .HasColumnName("receiver_phone");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("numeric")
                        .HasColumnName("shipping_fee");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_orders_user_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid?>("ProductId1")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id1");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("sub_total");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_order_items_product_id");

                    b.HasIndex("ProductId1")
                        .HasDatabaseName("ix_order_items_product_id1");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("EstimatedProductionDays")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_production_days");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<Guid>("ProductCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_category_id");

                    b.Property<ProductType>("ProductType")
                        .HasColumnType("product_type_enum")
                        .HasColumnName("product_type");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasDefaultValue(new byte[] { 0 })
                        .HasColumnName("row_version");

                    b.Property<string>("SKU")
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<string>("SampleImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("sample_image_url");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.Property<bool>("SupportsNfc")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_nfc");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("ProductCategoryId")
                        .HasDatabaseName("ix_products_product_category_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_product_categories");

                    b.ToTable("product_categories", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<bool>("IsThumbnail")
                        .HasColumnType("boolean")
                        .HasColumnName("is_thumbnail");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.HasKey("Id")
                        .HasName("pk_product_images");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_product_images_file_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_images_product_id");

                    b.ToTable("product_images", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.ScanHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Device")
                        .HasColumnType("text")
                        .HasColumnName("device");

                    b.Property<Guid>("GiftId")
                        .HasColumnType("uuid")
                        .HasColumnName("gift_id");

                    b.Property<string>("IPAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scanned_at");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_scan_histories");

                    b.HasIndex("GiftId")
                        .HasDatabaseName("ix_scan_histories_gift_id");

                    b.ToTable("scan_histories", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.UploadedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CloudinaryId")
                        .HasColumnType("text")
                        .HasColumnName("cloudinary_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double?>("Duration")
                        .HasColumnType("double precision")
                        .HasColumnName("duration");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<FileType>("FileType")
                        .HasColumnType("file_type_enum")
                        .HasColumnName("file_type");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("MimeType")
                        .HasColumnType("text")
                        .HasColumnName("mime_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_uploaded_files");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_uploaded_files_user_id");

                    b.ToTable("uploaded_files", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthProvider")
                        .HasColumnType("text")
                        .HasColumnName("auth_provider");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("ProviderId")
                        .HasColumnType("text")
                        .HasColumnName("provider_id");

                    b.Property<UserTier>("Tier")
                        .HasColumnType("user_tier_enum")
                        .HasColumnName("tier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.UserQuota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DailyLimit")
                        .HasColumnType("integer")
                        .HasColumnName("daily_limit");

                    b.Property<int>("DailyRequestsUsed")
                        .HasColumnType("integer")
                        .HasColumnName("daily_requests_used");

                    b.Property<DateTime>("LastResetDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reset_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_quotas");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_quotas_user_id");

                    b.ToTable("user_quotas", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.Ai3dRequest", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.UploadedFile", "UploadedFile")
                        .WithMany()
                        .HasForeignKey("UploadedFileId")
                        .HasConstraintName("fk_ai_3d_requests_uploaded_files_uploaded_file_id");

                    b.HasOne("CraftVision.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_3d_requests_users_user_id");

                    b.Navigation("UploadedFile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.AiChatMessage", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.UploadedFile", "ImageFile")
                        .WithMany()
                        .HasForeignKey("ImageFileId")
                        .HasConstraintName("fk_ai_chat_messages_uploaded_files_image_file_id");

                    b.HasOne("CraftVision.Domain.Entities.AiRequest", "Request")
                        .WithMany("Messages")
                        .HasForeignKey("RequestId")
                        .HasConstraintName("fk_ai_chat_messages_ai_requests_request_id");

                    b.HasOne("CraftVision.Domain.Entities.AiChatSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_chat_messages_ai_chat_sessions_session_id");

                    b.Navigation("ImageFile");

                    b.Navigation("Request");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.AiChatSession", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.User", "User")
                        .WithMany("ChatSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_chat_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.AiRequest", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.AiChatSession", "Session")
                        .WithMany("Requests")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_requests_ai_chat_sessions_session_id");

                    b.HasOne("CraftVision.Domain.Entities.UploadedFile", "UploadedFile")
                        .WithMany()
                        .HasForeignKey("UploadedFileId")
                        .HasConstraintName("fk_ai_requests_uploaded_files_uploaded_file_id");

                    b.HasOne("CraftVision.Domain.Entities.User", "User")
                        .WithMany("AiRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_requests_users_user_id");

                    b.Navigation("Session");

                    b.Navigation("UploadedFile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.DiyPlan", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.AiRequest", "Request")
                        .WithOne("DiyPlan")
                        .HasForeignKey("CraftVision.Domain.Entities.DiyPlan", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_diy_plans_ai_requests_request_id");

                    b.HasOne("CraftVision.Domain.Entities.User", "User")
                        .WithMany("DiyPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_diy_plans_users_user_id");

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.DiyPlanMaterial", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.DiyPlan", "DiyPlan")
                        .WithMany("PlanMaterials")
                        .HasForeignKey("DiyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_diy_plan_materials_diy_plans_diy_plan_id");

                    b.HasOne("CraftVision.Domain.Entities.KnowledgeMaterial", "Material")
                        .WithMany("DiyPlanMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_diy_plan_materials_knowledge_materials_material_id");

                    b.Navigation("DiyPlan");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.DiyPlanTutorial", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.DiyPlan", "DiyPlan")
                        .WithMany("PlanTutorials")
                        .HasForeignKey("DiyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_diy_plan_tutorials_diy_plans_diy_plan_id");

                    b.HasOne("CraftVision.Domain.Entities.KnowledgeTutorial", "Tutorial")
                        .WithMany("DiyPlanTutorials")
                        .HasForeignKey("TutorialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_diy_plan_tutorials_knowledge_tutorials_tutorial_id");

                    b.Navigation("DiyPlan");

                    b.Navigation("Tutorial");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.Gift", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.NfcTag", "NfcTag")
                        .WithOne("Gift")
                        .HasForeignKey("CraftVision.Domain.Entities.Gift", "NfcTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_gifts_nfc_tags_nfc_tag_id");

                    b.HasOne("CraftVision.Domain.Entities.OrderItem", "OrderItem")
                        .WithOne("Gift")
                        .HasForeignKey("CraftVision.Domain.Entities.Gift", "OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gifts_order_items_order_item_id");

                    b.Navigation("NfcTag");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.GiftAiProfile", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.GiftCategory", "GiftCategory")
                        .WithMany("GiftAiProfiles")
                        .HasForeignKey("GiftCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gift_ai_profiles_gift_categories_gift_category_id");

                    b.HasOne("CraftVision.Domain.Entities.Gift", "Gift")
                        .WithOne("AiProfile")
                        .HasForeignKey("CraftVision.Domain.Entities.GiftAiProfile", "GiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gift_ai_profiles_gifts_gift_id");

                    b.Navigation("Gift");

                    b.Navigation("GiftCategory");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.GiftMedia", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.UploadedFile", "File")
                        .WithMany("GiftMediaList")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gift_media_uploaded_files_file_id");

                    b.HasOne("CraftVision.Domain.Entities.Gift", "Gift")
                        .WithMany("MediaList")
                        .HasForeignKey("GiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gift_media_gifts_gift_id");

                    b.Navigation("File");

                    b.Navigation("Gift");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.GiftSuggestion", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.AiRequest", "Request")
                        .WithMany("Suggestions")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gift_suggestions_ai_requests_request_id");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.ImageAnalysisResult", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.UploadedFile", "UploadedFile")
                        .WithOne("ImageAnalysisResult")
                        .HasForeignKey("CraftVision.Domain.Entities.ImageAnalysisResult", "UploadedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_image_analysis_results_uploaded_files_uploaded_file_id");

                    b.Navigation("UploadedFile");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.MessageTemplate", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.GiftCategory", "GiftCategory")
                        .WithMany("MessageTemplates")
                        .HasForeignKey("GiftCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_templates_gift_categories_gift_category_id");

                    b.Navigation("GiftCategory");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.Order", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orders_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_orders_order_id");

                    b.HasOne("CraftVision.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_products_product_id");

                    b.HasOne("CraftVision.Domain.Entities.Product", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId1")
                        .HasConstraintName("fk_order_items_products_product_id1");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.Product", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_product_categories_product_category_id");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.UploadedFile", "File")
                        .WithMany("ProductImages")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_images_uploaded_files_file_id");

                    b.HasOne("CraftVision.Domain.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_images_products_product_id");

                    b.Navigation("File");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.ScanHistory", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.Gift", "Gift")
                        .WithMany("ScanHistories")
                        .HasForeignKey("GiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scan_histories_gifts_gift_id");

                    b.Navigation("Gift");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.UploadedFile", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.User", "User")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_uploaded_files_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.UserQuota", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.User", "User")
                        .WithOne("Quota")
                        .HasForeignKey("CraftVision.Domain.Entities.UserQuota", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_quotas_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.AiChatSession", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.AiRequest", b =>
                {
                    b.Navigation("DiyPlan");

                    b.Navigation("Messages");

                    b.Navigation("Suggestions");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.DiyPlan", b =>
                {
                    b.Navigation("PlanMaterials");

                    b.Navigation("PlanTutorials");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.Gift", b =>
                {
                    b.Navigation("AiProfile");

                    b.Navigation("MediaList");

                    b.Navigation("ScanHistories");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.GiftCategory", b =>
                {
                    b.Navigation("GiftAiProfiles");

                    b.Navigation("MessageTemplates");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.KnowledgeMaterial", b =>
                {
                    b.Navigation("DiyPlanMaterials");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.KnowledgeTutorial", b =>
                {
                    b.Navigation("DiyPlanTutorials");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.NfcTag", b =>
                {
                    b.Navigation("Gift");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.OrderItem", b =>
                {
                    b.Navigation("Gift");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ProductImages");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.UploadedFile", b =>
                {
                    b.Navigation("GiftMediaList");

                    b.Navigation("ImageAnalysisResult");

                    b.Navigation("ProductImages");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.User", b =>
                {
                    b.Navigation("AiRequests");

                    b.Navigation("ChatSessions");

                    b.Navigation("DiyPlans");

                    b.Navigation("Orders");

                    b.Navigation("Quota");

                    b.Navigation("UploadedFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
