// <auto-generated />
using System;
using System.Collections.Generic;
using CraftVision.Domain.Enums;
using CraftVision.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace CraftVision.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "difficulty_enum", new[] { "Easy", "Hard", "Medium" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "file_type_enum", new[] { "Image" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "material_unit_enum", new[] { "gram", "liter", "meter", "pack", "piece", "set" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "message_role_enum", new[] { "Assistant", "System", "User" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "option_level_enum", new[] { "Advanced", "Basic", "Intermediate" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "request_status_enum", new[] { "Completed", "Failed", "Pending" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_tier_enum", new[] { "Free", "Premium" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CraftVision.Domain.Entities.AiChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ImageFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_file_id");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.PrimitiveCollection<List<Guid>>("RetrievedContextIds")
                        .HasColumnType("uuid[]")
                        .HasColumnName("retrieved_context_ids");

                    b.Property<MessageRole>("Role")
                        .HasColumnType("message_role_enum")
                        .HasColumnName("role");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_used");

                    b.HasKey("Id")
                        .HasName("pk_ai_chat_messages");

                    b.HasIndex("ImageFileId")
                        .HasDatabaseName("ix_ai_chat_messages_image_file_id");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("ix_ai_chat_messages_request_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_ai_chat_messages_session_id");

                    b.ToTable("ai_chat_messages", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.AiChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_ai_chat_sessions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ai_chat_sessions_user_id");

                    b.ToTable("ai_chat_sessions", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.AiRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("ParsedIntent")
                        .HasColumnType("jsonb")
                        .HasColumnName("parsed_intent");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_text");

                    b.Property<int?>("RequestTokens")
                        .HasColumnType("integer")
                        .HasColumnName("request_tokens");

                    b.Property<int?>("ResponseTokens")
                        .HasColumnType("integer")
                        .HasColumnName("response_tokens");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<RequestStatus>("Status")
                        .HasColumnType("request_status_enum")
                        .HasColumnName("status");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("integer")
                        .HasColumnName("total_tokens");

                    b.Property<Guid?>("UploadedFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_file_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_ai_requests");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_ai_requests_session_id");

                    b.HasIndex("UploadedFileId")
                        .HasDatabaseName("ix_ai_requests_uploaded_file_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ai_requests_user_id");

                    b.ToTable("ai_requests", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.DiyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Difficulty?>("Difficulty")
                        .HasColumnType("difficulty_enum")
                        .HasColumnName("difficulty");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_cost");

                    b.Property<int?>("EstimatedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_minutes");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_selected");

                    b.Property<string>("MaterialsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("materials_json");

                    b.Property<string>("Occasion")
                        .HasColumnType("text")
                        .HasColumnName("occasion");

                    b.Property<OptionLevel?>("OptionLevel")
                        .HasColumnType("option_level_enum")
                        .HasColumnName("option_level");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("ShareSlug")
                        .HasColumnType("text")
                        .HasColumnName("share_slug");

                    b.Property<string>("StepsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("steps_json");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_diy_plans");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_diy_plans_request_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_diy_plans_user_id");

                    b.ToTable("diy_plans", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.DiyPlanMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DiyPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("diy_plan_id");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<string>("NameSnapshot")
                        .HasColumnType("text")
                        .HasColumnName("name_snapshot");

                    b.Property<decimal?>("PriceSnapshot")
                        .HasColumnType("numeric")
                        .HasColumnName("price_snapshot");

                    b.Property<string>("PurchaseUrlSnapshot")
                        .HasColumnType("text")
                        .HasColumnName("purchase_url_snapshot");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<string>("SearchKeywordsSnapshot")
                        .HasColumnType("text")
                        .HasColumnName("search_keywords_snapshot");

                    b.HasKey("Id")
                        .HasName("pk_diy_plan_materials");

                    b.HasIndex("DiyPlanId")
                        .HasDatabaseName("ix_diy_plan_materials_diy_plan_id");

                    b.HasIndex("MaterialId")
                        .HasDatabaseName("ix_diy_plan_materials_material_id");

                    b.ToTable("diy_plan_materials", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.DiyPlanTutorial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DiyPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("diy_plan_id");

                    b.Property<Guid>("TutorialId")
                        .HasColumnType("uuid")
                        .HasColumnName("tutorial_id");

                    b.HasKey("Id")
                        .HasName("pk_diy_plan_tutorials");

                    b.HasIndex("DiyPlanId")
                        .HasDatabaseName("ix_diy_plan_tutorials_diy_plan_id");

                    b.HasIndex("TutorialId")
                        .HasDatabaseName("ix_diy_plan_tutorials_tutorial_id");

                    b.ToTable("diy_plan_tutorials", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.ImageAnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("numeric")
                        .HasColumnName("confidence_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<List<string>>("DetectedColors")
                        .HasColumnType("text[]")
                        .HasColumnName("detected_colors");

                    b.PrimitiveCollection<List<string>>("DetectedMaterials")
                        .HasColumnType("text[]")
                        .HasColumnName("detected_materials");

                    b.PrimitiveCollection<List<string>>("DetectedTechnique")
                        .HasColumnType("text[]")
                        .HasColumnName("detected_technique");

                    b.Property<string>("RawVisionResponse")
                        .HasColumnType("text")
                        .HasColumnName("raw_vision_response");

                    b.Property<Guid>("UploadedFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_file_id");

                    b.HasKey("Id")
                        .HasName("pk_image_analysis_results");

                    b.HasIndex("UploadedFileId")
                        .IsUnique()
                        .HasDatabaseName("ix_image_analysis_results_uploaded_file_id");

                    b.ToTable("image_analysis_results", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.KnowledgeMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("CurrentPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("current_price");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checked_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PurchaseUrl")
                        .HasColumnType("text")
                        .HasColumnName("purchase_url");

                    b.Property<string>("SearchKeywords")
                        .HasColumnType("text")
                        .HasColumnName("search_keywords");

                    b.Property<MaterialUnit?>("Unit")
                        .HasColumnType("material_unit_enum")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_materials");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_knowledge_materials_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("knowledge_materials", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.KnowledgeTutorial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Difficulty?>("Difficulty")
                        .HasColumnType("difficulty_enum")
                        .HasColumnName("difficulty");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<int?>("EstimatedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_minutes");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text")
                        .HasColumnName("video_url");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_tutorials");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_knowledge_tutorials_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("knowledge_tutorials", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.UploadedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<FileType>("FileType")
                        .HasColumnType("file_type_enum")
                        .HasColumnName("file_type");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_uploaded_files");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_uploaded_files_user_id");

                    b.ToTable("uploaded_files", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthProvider")
                        .HasColumnType("text")
                        .HasColumnName("auth_provider");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("ProviderId")
                        .HasColumnType("text")
                        .HasColumnName("provider_id");

                    b.Property<UserTier>("Tier")
                        .HasColumnType("user_tier_enum")
                        .HasColumnName("tier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.UserQuota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DailyLimit")
                        .HasColumnType("integer")
                        .HasColumnName("daily_limit");

                    b.Property<int>("DailyRequestsUsed")
                        .HasColumnType("integer")
                        .HasColumnName("daily_requests_used");

                    b.Property<DateTime>("LastResetDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reset_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_quotas");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_quotas_user_id");

                    b.ToTable("user_quotas", (string)null);
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.AiChatMessage", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.UploadedFile", "ImageFile")
                        .WithMany()
                        .HasForeignKey("ImageFileId")
                        .HasConstraintName("fk_ai_chat_messages_uploaded_files_image_file_id");

                    b.HasOne("CraftVision.Domain.Entities.AiRequest", "Request")
                        .WithMany("Messages")
                        .HasForeignKey("RequestId")
                        .HasConstraintName("fk_ai_chat_messages_ai_requests_request_id");

                    b.HasOne("CraftVision.Domain.Entities.AiChatSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_chat_messages_ai_chat_sessions_session_id");

                    b.Navigation("ImageFile");

                    b.Navigation("Request");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.AiChatSession", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.User", "User")
                        .WithMany("ChatSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_chat_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.AiRequest", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.AiChatSession", "Session")
                        .WithMany("Requests")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_requests_ai_chat_sessions_session_id");

                    b.HasOne("CraftVision.Domain.Entities.UploadedFile", "UploadedFile")
                        .WithMany()
                        .HasForeignKey("UploadedFileId")
                        .HasConstraintName("fk_ai_requests_uploaded_files_uploaded_file_id");

                    b.HasOne("CraftVision.Domain.Entities.User", "User")
                        .WithMany("AiRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_requests_users_user_id");

                    b.Navigation("Session");

                    b.Navigation("UploadedFile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.DiyPlan", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.AiRequest", "Request")
                        .WithOne("DiyPlan")
                        .HasForeignKey("CraftVision.Domain.Entities.DiyPlan", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_diy_plans_ai_requests_request_id");

                    b.HasOne("CraftVision.Domain.Entities.User", "User")
                        .WithMany("DiyPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_diy_plans_users_user_id");

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.DiyPlanMaterial", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.DiyPlan", "DiyPlan")
                        .WithMany("PlanMaterials")
                        .HasForeignKey("DiyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_diy_plan_materials_diy_plans_diy_plan_id");

                    b.HasOne("CraftVision.Domain.Entities.KnowledgeMaterial", "Material")
                        .WithMany("DiyPlanMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_diy_plan_materials_knowledge_materials_material_id");

                    b.Navigation("DiyPlan");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.DiyPlanTutorial", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.DiyPlan", "DiyPlan")
                        .WithMany("PlanTutorials")
                        .HasForeignKey("DiyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_diy_plan_tutorials_diy_plans_diy_plan_id");

                    b.HasOne("CraftVision.Domain.Entities.KnowledgeTutorial", "Tutorial")
                        .WithMany("DiyPlanTutorials")
                        .HasForeignKey("TutorialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_diy_plan_tutorials_knowledge_tutorials_tutorial_id");

                    b.Navigation("DiyPlan");

                    b.Navigation("Tutorial");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.ImageAnalysisResult", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.UploadedFile", "UploadedFile")
                        .WithOne("ImageAnalysisResult")
                        .HasForeignKey("CraftVision.Domain.Entities.ImageAnalysisResult", "UploadedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_image_analysis_results_uploaded_files_uploaded_file_id");

                    b.Navigation("UploadedFile");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.UploadedFile", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.User", "User")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_uploaded_files_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.UserQuota", b =>
                {
                    b.HasOne("CraftVision.Domain.Entities.User", "User")
                        .WithOne("Quota")
                        .HasForeignKey("CraftVision.Domain.Entities.UserQuota", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_quotas_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.AiChatSession", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.AiRequest", b =>
                {
                    b.Navigation("DiyPlan");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.DiyPlan", b =>
                {
                    b.Navigation("PlanMaterials");

                    b.Navigation("PlanTutorials");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.KnowledgeMaterial", b =>
                {
                    b.Navigation("DiyPlanMaterials");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.KnowledgeTutorial", b =>
                {
                    b.Navigation("DiyPlanTutorials");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.UploadedFile", b =>
                {
                    b.Navigation("ImageAnalysisResult");
                });

            modelBuilder.Entity("CraftVision.Domain.Entities.User", b =>
                {
                    b.Navigation("AiRequests");

                    b.Navigation("ChatSessions");

                    b.Navigation("DiyPlans");

                    b.Navigation("Quota");

                    b.Navigation("UploadedFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
